CREATE TABLE C_ESTADOS_REGISTROS
(
  CES_PK_ESTADO    NUMBER(10),
  CES_NOMBRE       VARCHAR2(400 BYTE),
  CES_DESCRIPCION  VARCHAR2(400 BYTE),
  CONSTRAINT C_ESTADOS_REGISTROS_PK
  PRIMARY KEY
  (CES_PK_ESTADO)
  ENABLE VALIDATE
);


CREATE TABLE C_TIENDAS
(
  CTI_PK_TIENDA    NUMBER(10),
  CTI_NOMBRE       VARCHAR2(200 BYTE),
  CTI_DESCRIPCION  VARCHAR2(4000 BYTE),
  CTI_FK_ESTADO    NUMBER(10),
  CTI_FECHA_AUDIT  DATE                         DEFAULT sysdate,
  CONSTRAINT C_TIENDAS_PK
  PRIMARY KEY
  (CTI_PK_TIENDA)
  ENABLE VALIDATE,
  CONSTRAINT C_TIENDAS_R01 
  FOREIGN KEY (CTI_FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE
);


CREATE TABLE C_TIPOS_USUARIO
(
  CTU_PK_TIPO_USUARIO  NUMBER(10),
  CTU_NOMBRE           VARCHAR2(400 BYTE),
  CTU_DESCRIPCION      VARCHAR2(400 BYTE),
  CTU_FK_ESTADO        NUMBER(10),
  CONSTRAINT C_TIPOS_USUARIO_PK
  PRIMARY KEY
  (CTU_PK_TIPO_USUARIO)
  ENABLE VALIDATE,
  CONSTRAINT C_TIPOS_USUARIO_R01 
  FOREIGN KEY (CTU_FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE
);


CREATE TABLE T_PRODUCTOS
(
  TPR_PK_PRODUCTO     NUMBER,
  TPR_NOMBRE          VARCHAR2(400 BYTE),
  TPR_DESCRIPCION     VARCHAR2(4000 BYTE),
  TPR_PRECIO          NUMBER(10,5),
  TPR_IMAGEN          VARCHAR2(4000 BYTE),
  TPR_FK_ESTADO       NUMBER(10),
  TPR_FECHA_REGISTRO  DATE                      DEFAULT sysdate,
  CONSTRAINT T_PRODUCTOS_PK
  PRIMARY KEY
  (TPR_PK_PRODUCTO)
  ENABLE VALIDATE,
  CONSTRAINT T_PRODUCTOS_R01 
  FOREIGN KEY (TPR_FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE
);


CREATE TABLE T_TIENDAS
(
  TTI_PK_TIENDA      NUMBER(10),
  TTI_NOMBRE_TIENDA  VARCHAR2(400 BYTE),
  TTI_DESCRIPCION    VARCHAR2(400 BYTE),
  TTI_UBICACION      VARCHAR2(4000 BYTE),
  TTI_IMAGEN         VARCHAR2(4000 BYTE),
  TTI_FK_ESTADO      NUMBER(10),
  CONSTRAINT T_TIENDAS_PK
  PRIMARY KEY
  (TTI_PK_TIENDA)
  ENABLE VALIDATE,
  CONSTRAINT T_TIENDAS_R01 
  FOREIGN KEY (TTI_FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE
);


CREATE TABLE T_USUARIOS
(
  TUS_PK_USUARIO       NUMBER(10),
  TUS_NOMBRE           VARCHAR2(400 BYTE),
  TUS_APELLIDOS        VARCHAR2(400 BYTE),
  TUS_USERNAME         VARCHAR2(400 BYTE),
  TUS_PASSWORD         VARCHAR2(400 BYTE),
  TUS_EMAIL            VARCHAR2(400 BYTE),
  TUS_FK_ESTADO        NUMBER(10),
  TUS_FK_TIPO_USUARIO  NUMBER(10),
  CONSTRAINT T_USUARIOS_PK
  PRIMARY KEY
  (TUS_PK_USUARIO)
  ENABLE VALIDATE,
  CONSTRAINT T_USUARIOS_R01 
  FOREIGN KEY (TUS_FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE,
  CONSTRAINT T_USUARIOS_R02 
  FOREIGN KEY (TUS_FK_TIPO_USUARIO) 
  REFERENCES C_TIPOS_USUARIO (CTU_PK_TIPO_USUARIO)
  ENABLE VALIDATE
);


CREATE TABLE C_CATEGORIAS
(
  CCA_PK_CATEGORIA  NUMBER(10),
  CCA_NOMBRE        VARCHAR2(400 BYTE),
  CCA_DESCRIPCION   VARCHAR2(4000 BYTE),
  CCA_FK_ESTADO     NUMBER(10),
  CONSTRAINT C_CATEGORIAS_PK
  PRIMARY KEY
  (CCA_PK_CATEGORIA)
  ENABLE VALIDATE,
  CONSTRAINT C_CATEGORIAS_R01 
  FOREIGN KEY (CCA_FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE
);


CREATE TABLE T_CARRITO
(
  TCA_PK_CARRITO          NUMBER(10),
  TCA_FK_USUARIO          NUMBER(10),
  TCA_FK_ESTADO_CARRITO   NUMBER(10),
  TCA_FK_ESTADO           NUMBER(10),
  TCA_IMPORTE_PAGADO      NUMBER(10,5),
  TCA_TARJETA_PAGO        VARCHAR2(400 BYTE),
  TCA_FECHA_AUTORIZACION  VARCHAR2(400 BYTE),
  TCA_NUM_REFERENCIA      VARCHAR2(400 BYTE),
  TCA_BANCO               VARCHAR2(400 BYTE),
  TCA_REQUIERE_FACTURA    NUMBER(10),
  TCA_FK_TIENDA           NUMBER(10),
  CONSTRAINT T_CARRITO_PK
  PRIMARY KEY
  (TCA_PK_CARRITO)
  ENABLE VALIDATE,
  CONSTRAINT T_CARRITO_R01 
  FOREIGN KEY (TCA_FK_USUARIO) 
  REFERENCES T_USUARIOS (TUS_PK_USUARIO)
  ENABLE VALIDATE,
  CONSTRAINT T_CARRITO_R02 
  FOREIGN KEY (TCA_FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE,
  CONSTRAINT T_CARRITO_R03 
  FOREIGN KEY (TCA_FK_TIENDA) 
  REFERENCES C_TIENDAS (CTI_PK_TIENDA)
  ENABLE VALIDATE
);


CREATE TABLE T_CATEGORIAS_PRODUCTOS
(
  TCP_PK_CATEGORIA_PRODUCTO  NUMBER(10),
  TCP_FK_CATEGORIA           NUMBER(10),
  TCP_FK_PRODUCTO            NUMBER(10),
  TCP_FK_ESTADO              NUMBER(10),
  CONSTRAINT T_CATEGORIAS_PRODUCTOS_PK
  PRIMARY KEY
  (TCP_PK_CATEGORIA_PRODUCTO)
  ENABLE VALIDATE,
  CONSTRAINT T_CATEGORIAS_PRODUCTOS_R01 
  FOREIGN KEY (TCP_FK_CATEGORIA) 
  REFERENCES C_CATEGORIAS (CCA_PK_CATEGORIA)
  ENABLE VALIDATE,
  CONSTRAINT T_CATEGORIAS_PRODUCTOS_R02 
  FOREIGN KEY (TCP_FK_PRODUCTO) 
  REFERENCES T_PRODUCTOS (TPR_PK_PRODUCTO)
  ENABLE VALIDATE,
  CONSTRAINT T_CATEGORIAS_PRODUCTOS_R03 
  FOREIGN KEY (TCP_FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE
);


CREATE TABLE T_DUENOS_TIENDAS
(
  TDT_PK_DUENO    NUMBER(10),
  TDT_FK_USUARIO  NUMBER(10),
  TDT_FK_TIENDA   NUMBER(10),
  TDT_FK_ESTADO   NUMBER(10),
  CONSTRAINT T_DUENOS_TIENDAS_PK
  PRIMARY KEY
  (TDT_PK_DUENO)
  ENABLE VALIDATE,
  CONSTRAINT T_DUENOS_TIENDAS_R01 
  FOREIGN KEY (TDT_FK_USUARIO) 
  REFERENCES T_USUARIOS (TUS_PK_USUARIO)
  ENABLE VALIDATE,
  CONSTRAINT T_DUENOS_TIENDAS_R02 
  FOREIGN KEY (TDT_FK_TIENDA) 
  REFERENCES T_TIENDAS (TTI_PK_TIENDA)
  ENABLE VALIDATE,
  CONSTRAINT T_DUENOS_TIENDAS_R03 
  FOREIGN KEY (TDT_FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE
);


CREATE TABLE T_ELEMENTO_CARRITO
(
  TEC_PK_ELEMENTO_CARRITO  NUMBER(10),
  TEC_FK_CARRITO           NUMBER(10),
  TEC_FK_PRODUCTO          NUMBER(10),
  TEC_CANTIDAD             NUMBER(10),
  TEC_FK_ESTADO            NUMBER(10,5),
  CONSTRAINT T_ELEMENTO_CARRITO_PK
  PRIMARY KEY
  (TEC_PK_ELEMENTO_CARRITO)
  ENABLE VALIDATE,
  CONSTRAINT T_ELEMENTO_CARRITO_R01 
  FOREIGN KEY (TEC_FK_CARRITO) 
  REFERENCES T_CARRITO (TCA_PK_CARRITO)
  ENABLE VALIDATE,
  CONSTRAINT T_ELEMENTO_CARRITO_R02 
  FOREIGN KEY (TEC_FK_PRODUCTO) 
  REFERENCES T_PRODUCTOS (TPR_PK_PRODUCTO)
  ENABLE VALIDATE,
  CONSTRAINT T_ELEMENTO_CARRITO_R03 
  FOREIGN KEY (TEC_FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE
);


CREATE TABLE T_INVENTARIOS
(
  TIN_PK_REGINVENTARIO  NUMBER(10),
  TIN_FK_TIENDA         NUMBER(10),
  TIN_FK_PRODUCTO       NUMBER(10),
  TIN_CANTIDAD          NUMBER(10),
  TIN_DESCRIPCION       VARCHAR2(4000 BYTE),
  FK_ESTADO             NUMBER(10),
  CONSTRAINT T_INVENTARIOS_PK
  PRIMARY KEY
  (TIN_PK_REGINVENTARIO)
  ENABLE VALIDATE,
  CONSTRAINT T_INVENTARIOS_R01 
  FOREIGN KEY (TIN_FK_TIENDA) 
  REFERENCES T_TIENDAS (TTI_PK_TIENDA)
  ENABLE VALIDATE,
  CONSTRAINT T_INVENTARIOS_R02 
  FOREIGN KEY (TIN_FK_PRODUCTO) 
  REFERENCES T_PRODUCTOS (TPR_PK_PRODUCTO)
  ENABLE VALIDATE,
  CONSTRAINT T_INVENTARIOS_R03 
  FOREIGN KEY (FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE
);


CREATE TABLE T_PAGO
(
  TPA_PK_PAGO             NUMBER(10),
  TPA_FK_USUARIO          NUMBER(10),
  TPA_FK_CARRITO          NUMBER(10),
  TPA_FK_ESTADO_PAGO      NUMBER(10),
  TPA_IMPORTE_PAGADO      NUMBER(10,5),
  TPA_TARJETA_PAGO        VARCHAR2(400 BYTE),
  TPA_FECHA_AUTORIZACION  DATE,
  TPA_NUM_REFERENCIA      VARCHAR2(400 BYTE),
  TPA_BANCO               VARCHAR2(400 BYTE),
  TPA_REQUIERE_FACTURA    NUMBER(1),
  CONSTRAINT T_PAGO_PK
  PRIMARY KEY
  (TPA_PK_PAGO)
  ENABLE VALIDATE,
  CONSTRAINT T_PAGO_R01 
  FOREIGN KEY (TPA_FK_USUARIO) 
  REFERENCES T_USUARIOS (TUS_PK_USUARIO)
  ENABLE VALIDATE,
  CONSTRAINT T_PAGO_R02 
  FOREIGN KEY (TPA_FK_CARRITO) 
  REFERENCES T_CARRITO (TCA_PK_CARRITO)
  ENABLE VALIDATE
);


CREATE TABLE T_DETALLE_PAGO
(
  TDP_PK_DETALLE_PAGO  NUMBER(10),
  TDP_FK_PAGO          NUMBER(10),
  TDP_FK_PRODUCTO      NUMBER(10),
  TDP_CANTIDAD         NUMBER(10),
  TDP_PRECIO_UNITARIO  NUMBER(10,5),
  TDP_FK_ESTADO        NUMBER(10),
  CONSTRAINT T_DETALLE_PAGO_PK
  PRIMARY KEY
  (TDP_PK_DETALLE_PAGO)
  ENABLE VALIDATE,
  CONSTRAINT T_DETALLE_PAGO_R01 
  FOREIGN KEY (TDP_FK_PAGO) 
  REFERENCES T_PAGO (TPA_PK_PAGO)
  ENABLE VALIDATE,
  CONSTRAINT T_DETALLE_PAGO_R02 
  FOREIGN KEY (TDP_FK_PRODUCTO) 
  REFERENCES T_PRODUCTOS (TPR_PK_PRODUCTO)
  ENABLE VALIDATE,
  CONSTRAINT T_DETALLE_PAGO_R03 
  FOREIGN KEY (TDP_FK_ESTADO) 
  REFERENCES C_ESTADOS_REGISTROS (CES_PK_ESTADO)
  ENABLE VALIDATE
);
